# Model arguments
model_name_or_path: alignment-handbook/model_checkpoints/llama3.2-3b-instruct-sft-transfer-v5-lineno/checkpoint-6626/
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  teledia-cmu/ruff-meta-linting-dpo-llama3.2_3b_transfer_v5_lineno_SFT_step_6626_violations_only: 1.0
  teledia-cmu/ruff-meta-linting-dpo-llama3.2_3b_transfer_v5_lineno_SFT_step_6626_no_violations_only: 0.02
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
eval_strategy: steps
eval_steps: 200
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: null
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 3500
# max_prompt_length: 1024
num_train_epochs: 1
optim: adamw_torch
output_dir: model_checkpoints/llama3.2-3b-instruct-dpo-transfer-v5-lineno_no_violations_0.02
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "steps"
save_steps: 200
seed: 42
warmup_ratio: 0.1